// flow-typed signature: c4bd542c1e5f13d49c3dd04a3f07c06a
// flow-typed version: <<STUB>>/css-scroll-snap-polyfill_v^0.1.2/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-scroll-snap-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-scroll-snap-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'css-scroll-snap-polyfill/dist/css-scroll-snap-polyfill.cjs' {
  declare module.exports: any;
}

declare module 'css-scroll-snap-polyfill/dist/css-scroll-snap-polyfill.esm' {
  declare module.exports: any;
}

declare module 'css-scroll-snap-polyfill/dist/css-scroll-snap-polyfill.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'css-scroll-snap-polyfill/dist/css-scroll-snap-polyfill.cjs.js' {
  declare module.exports: $Exports<'css-scroll-snap-polyfill/dist/css-scroll-snap-polyfill.cjs'>;
}
declare module 'css-scroll-snap-polyfill/dist/css-scroll-snap-polyfill.esm.js' {
  declare module.exports: $Exports<'css-scroll-snap-polyfill/dist/css-scroll-snap-polyfill.esm'>;
}
declare module 'css-scroll-snap-polyfill/dist/css-scroll-snap-polyfill.umd.js' {
  declare module.exports: $Exports<'css-scroll-snap-polyfill/dist/css-scroll-snap-polyfill.umd'>;
}
