// flow-typed signature: 1e19f169e9ad3879971ac5870e679954
// flow-typed version: <<STUB>>/rc-trigger_v^2.4.2/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rc-trigger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rc-trigger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rc-trigger/es/index' {
  declare module.exports: any;
}

declare module 'rc-trigger/es/LazyRenderBox' {
  declare module.exports: any;
}

declare module 'rc-trigger/es/mock' {
  declare module.exports: any;
}

declare module 'rc-trigger/es/Popup' {
  declare module.exports: any;
}

declare module 'rc-trigger/es/PopupInner' {
  declare module.exports: any;
}

declare module 'rc-trigger/es/utils' {
  declare module.exports: any;
}

declare module 'rc-trigger/lib/index' {
  declare module.exports: any;
}

declare module 'rc-trigger/lib/LazyRenderBox' {
  declare module.exports: any;
}

declare module 'rc-trigger/lib/mock' {
  declare module.exports: any;
}

declare module 'rc-trigger/lib/Popup' {
  declare module.exports: any;
}

declare module 'rc-trigger/lib/PopupInner' {
  declare module.exports: any;
}

declare module 'rc-trigger/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rc-trigger/es/index.js' {
  declare module.exports: $Exports<'rc-trigger/es/index'>;
}
declare module 'rc-trigger/es/LazyRenderBox.js' {
  declare module.exports: $Exports<'rc-trigger/es/LazyRenderBox'>;
}
declare module 'rc-trigger/es/mock.js' {
  declare module.exports: $Exports<'rc-trigger/es/mock'>;
}
declare module 'rc-trigger/es/Popup.js' {
  declare module.exports: $Exports<'rc-trigger/es/Popup'>;
}
declare module 'rc-trigger/es/PopupInner.js' {
  declare module.exports: $Exports<'rc-trigger/es/PopupInner'>;
}
declare module 'rc-trigger/es/utils.js' {
  declare module.exports: $Exports<'rc-trigger/es/utils'>;
}
declare module 'rc-trigger/lib/index.js' {
  declare module.exports: $Exports<'rc-trigger/lib/index'>;
}
declare module 'rc-trigger/lib/LazyRenderBox.js' {
  declare module.exports: $Exports<'rc-trigger/lib/LazyRenderBox'>;
}
declare module 'rc-trigger/lib/mock.js' {
  declare module.exports: $Exports<'rc-trigger/lib/mock'>;
}
declare module 'rc-trigger/lib/Popup.js' {
  declare module.exports: $Exports<'rc-trigger/lib/Popup'>;
}
declare module 'rc-trigger/lib/PopupInner.js' {
  declare module.exports: $Exports<'rc-trigger/lib/PopupInner'>;
}
declare module 'rc-trigger/lib/utils.js' {
  declare module.exports: $Exports<'rc-trigger/lib/utils'>;
}
